vscode:
  extensions:
    - dracula-theme.theme-dracula
    - 42Crunch.vscode-openapi
    - asyncapi.asyncapi-preview
    - github.vscode-github-actions
    - usernamehw.errorlens
    - oderwat.indent-rainbow
    - ms-azuretools.vscode-docker
    - stoplight.spectral