version: '3.9'
services:
  prism:
    image: stoplight/prism:4
    command: 'mock -h 0.0.0.0 /tmp/dog_walker.1.oas.yaml'
    volumes:
      - ./dog_walker.1.oas.yaml:/tmp/dog_walker.1.oas.yaml:ro
    ports:
      # Serve the mocked API locally as available on port 8080
      - '8080:4010'